services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "9432:5432"
  web:
    stdin_open: true
    tty: true
    build: .
    command: bash -c "python manage.py migrate && python manage.py create_users_and_groups && python manage.py runserver 0.0.0.0:8654"
    volumes:
      - .:/code
    ports:
      - "8654:8654"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  test:
    stdin_open: true
    tty: true
    build: .
    command: bash -c "black . && flake8 . && mypy . && ./manage.py test"
    volumes:
      - .:/code
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    profiles: ['test']